### ISSUE TITLE
brand identity

### ISSUE THREAD

**Issue by isysd** [GitGuild/gitguild_website#2]
Determine colors, themes, and other elements to use in brand.

**Comment by isysd** [comment]
The git guild brand should follow the theme of guilds from the middle ages, and use a heraldic shield. Examples:

![guilds](http://1.bp.blogspot.com/_Dwl8JecHnvw/TG_C3XvubLI/AAAAAAAAAFk/GBIJLnghyS4/s1600/medieval+guilds.jpg)

The colors should be much simpler and more modern, however. Perhaps white and blue, but a lighter blue than the blue in Deginner's logo.

![Deginner](http://i.imgur.com/MINlVoa.png)

The imagery on the shield should represent the topic of software development. Perhaps a honey badger, or a penguin, or simply "1" and "0" on the two sides of the shield, representing binary code. Would like to see different concepts, with these different options. Imagery examples:

![honey badger](https://images.duckduckgo.com/iu/?u=http%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.Mc7ce0b3795e00e3953232d3b9a867d43o0%26pid%3D15.1&f=1)

![tux](https://duckduckgo.com/i/e88f92bc.png)

![binary](https://images.duckduckgo.com/iu/?u=http%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.M964e0d54e089638b95f0ec2705f0ed20o0%26pid%3D15.1&f=1)

**Comment by isysd** [comment]
@mobymarto @luisvillara The brand is ready for you guys to start. Please let me know if you have questions.

**Comment by isysd** [comment]
@luisvillara @mobymarto what's the status on this? Can we please get it ready ASAP? I need to have it on banners for a press event in less than 1 month!

**Comment by RandyHilarski** [comment]
I do believe a one color logo is best. Something that can be used on Quotes and Images and still look good on almost any color background. A two color logo can work also as The Dollar Vigilante shows. 

![fort-galt-quote01](https://cloud.githubusercontent.com/assets/17459914/15942782/92b2fb94-2e4b-11e6-932a-527eabb5c99e.jpg)
![jeff-berwick-human-advancement-doug-casey](https://cloud.githubusercontent.com/assets/17459914/15942820/c11f8970-2e4b-11e6-909b-e62df9509c13.jpg)

**Comment by isysd** [comment]
# Git Guild Bounty Program

| Total | Dev               | Sales | Reporter | Tester(s) | Maintainer | Documenter |
|--------|------------------|---------|-------------|------------|-----------------|----------------|
|N/A    | assignee(s)   | N/A  | @isysd | @isysd, @d3brouille | @isysd  | @d3brouille |
| $166.67 | $100.00 | $0.00 | $8.33 | $33.33 | $8.33 |

**Comment by isysd** [comment]
[Imgur](http://i.imgur.com/1Ccz7KO.png)

^^^ Plain version. Chose blue as the secondary color and have more formats including SVG.
