### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by isysd** [GitGuild/gitguild_website#3]
The git guild needs a logo of its own. Dependent on brand identity https://github.com/deginner/gitguild_website/issues/2.

**Comment by isysd** [comment]
For the logo, see the notes in https://github.com/deginner/gitguild_website/issues/2.

**Comment by isysd** [comment]
[logo](http://i.imgur.com/1Ccz7KO.png) Black and white, but obviously it can be colored any way we choose. :)

**Comment by ChrisSavoie** [comment]
I know this wasn't asked for.. but what about something like this?

![Gitguild Logo Concept](https://cloud.githubusercontent.com/assets/6020462/17468302/3b9fff9e-5cec-11e6-8f0f-25a80feeadb0.png)

**Comment by isysd** [comment]
@ChrisSavoie I like the concept, but we're already committed to the other. We have t-shirts, and banners in production. Hosting a startup event in 9 days. Just need to get a one pager up before then!
