### ISSUE TITLE
wireframes

### ISSUE THREAD

**Issue by isysd** [GitGuild/gitguild_website#4]
Create wireframes for the gitguild.com MVP site. Should include the following sections/elements:

 + [ ] Logo, top menu, front page content areas for copy and/or graphics
 + [ ] Projects section on home page linking to project pages
 + [ ] Project pages template (i.e. CTMs, Trade Manager)
 + [ ] Partners (Dash, Bitt, TigoCTM, Coinapult, Crypto Capital, etc.)
 + [ ] Contact form

**Comment by isysd** [comment]
@glenkow please consult with @ChrisSavoie on these wireframes, as needed. I know you also start with wireframes, in your copy writing work...

**Comment by isysd** [comment]
@glenkow has already created first draft wireframes. He promised to share during meeting last week.

**Comment by ChrisSavoie** [comment]
Hey @glenkow , please share at your earliest convenience. I'll be diving into this task this evening.

**Comment by ChrisSavoie** [comment]
Having trouble finding a copy of the logo. Should I rip it from the Q3 Page in the wiki, or perhaps do you have a png or svg file available somewhere?

**Comment by isysd** [comment]
Hi my bad @ChrisSavoie. I temporarily put them here

https://github.com/isysd/gitguild_gg_data/tree/master/images

Will find a better home for stuff like this...

**Comment by ChrisSavoie** [comment]
The 'partners' item [listed here](https://github.com/GitGuild/gitguild_website/issues/4#issue-167409314) ends with "etcetera" would you like to include more?

**Comment by isysd** [comment]
No, this is good for now. We have some catchup PR to do with these existing ones. :+1:
